[2025-02-23T19:16:11.698+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T18:57:50.092826+00:00 [queued]>
[2025-02-23T19:16:11.714+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T18:57:50.092826+00:00 [queued]>
[2025-02-23T19:16:11.715+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-23T19:16:11.734+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_to_hdfs> on 2025-02-23 18:57:50.092826+00:00
[2025-02-23T19:16:11.742+0000] {standard_task_runner.py:57} INFO - Started process 82671 to run task
[2025-02-23T19:16:11.745+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_crypto_data_and_upload_to_hdfs', 'upload_to_hdfs', 'manual__2025-02-23T18:57:50.092826+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data.py', '--cfg-path', '/tmp/tmpf_26ous5']
[2025-02-23T19:16:11.750+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask upload_to_hdfs
[2025-02-23T19:16:11.834+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T18:57:50.092826+00:00 [running]> on host 95f034191b67
[2025-02-23T19:16:11.926+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_crypto_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T18:57:50.092826+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T18:57:50.092826+00:00'
[2025-02-23T19:16:11.929+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-23T19:16:11.932+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'script -q /dev/null bash -c "docker cp /tmp/crypto_historical_data.csv namenode:/tmp/crypto_historical_data.csv && docker exec -it -u root namenode bash -c "hdfs dfs -put -f /tmp/crypto_historical_data.csv /user/hadoop/crypto_historical_data.csv""']
[2025-02-23T19:16:11.958+0000] {subprocess.py:86} INFO - Output:
[2025-02-23T19:16:11.976+0000] {subprocess.py:93} INFO - script: invalid option -- 'p'
[2025-02-23T19:16:11.977+0000] {subprocess.py:93} INFO - Try 'script --help' for more information.
[2025-02-23T19:16:11.978+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-23T19:16:11.996+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-23T19:16:12.001+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_crypto_data_and_upload_to_hdfs, task_id=upload_to_hdfs, execution_date=20250223T185750, start_date=20250223T191611, end_date=20250223T191612
[2025-02-23T19:16:12.015+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task upload_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 82671)
[2025-02-23T19:16:12.041+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-23T19:16:12.066+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
