[2025-02-26T15:27:54.228+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-26T15:27:47.608696+00:00 [queued]>
[2025-02-26T15:27:54.245+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-26T15:27:47.608696+00:00 [queued]>
[2025-02-26T15:27:54.246+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T15:27:54.266+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-26 15:27:47.608696+00:00
[2025-02-26T15:27:54.276+0000] {standard_task_runner.py:57} INFO - Started process 90362 to run task
[2025-02-26T15:27:54.280+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_processing_mapreduce', 'run_mapreduce_job', 'manual__2025-02-26T15:27:47.608696+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/transform_data.py', '--cfg-path', '/tmp/tmp44pmvxzu']
[2025-02-26T15:27:54.284+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask run_mapreduce_job
[2025-02-26T15:27:54.401+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-26T15:27:47.608696+00:00 [running]> on host 8f39f5b11fbf
[2025-02-26T15:27:54.546+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-26T15:27:54.604+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_processing_mapreduce' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T15:27:47.608696+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T15:27:47.608696+00:00'
[2025-02-26T15:27:54.607+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T15:27:54.611+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        cd /home \n        docker exec namenode hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar           -input /user/root/crypto/YYYY=2025/MM=02/DD=26/crypto_historical_data.csv           -output /user/root/crypto/processed/YYYY=2025/MM=02/DD=26           -mapper mapper.py           -reducer reducer.py           -file /home/mapper.py           -file /home/reducer.py\n        ']
[2025-02-26T15:27:54.623+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T15:27:56.821+0000] {subprocess.py:93} INFO - 2025-02-26 15:27:56,817 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-26T15:27:58.529+0000] {subprocess.py:93} INFO - packageJobJar: [/home/mapper.py, /home/reducer.py] [] /tmp/streamjob6144226955971464295.jar tmpDir=null
[2025-02-26T15:27:58.549+0000] {subprocess.py:93} INFO - Exception in thread "main" java.io.IOException: expanding mapper.py would create file outside of /.
[2025-02-26T15:27:58.551+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:199)
[2025-02-26T15:27:58.553+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.StreamJob.submitAndMonitorJob(StreamJob.java:1011)
[2025-02-26T15:27:58.553+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.StreamJob.run(StreamJob.java:135)
[2025-02-26T15:27:58.554+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
[2025-02-26T15:27:58.555+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
[2025-02-26T15:27:58.555+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.HadoopStreaming.main(HadoopStreaming.java:50)
[2025-02-26T15:27:58.556+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-26T15:27:58.557+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-26T15:27:58.557+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-26T15:27:58.558+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-26T15:27:58.558+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
[2025-02-26T15:27:58.559+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
[2025-02-26T15:27:58.937+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-26T15:27:58.963+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T15:27:58.971+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_processing_mapreduce, task_id=run_mapreduce_job, execution_date=20250226T152747, start_date=20250226T152754, end_date=20250226T152758
[2025-02-26T15:27:58.991+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 1.; 90362)
[2025-02-26T15:27:59.044+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T15:27:59.094+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
