[2025-02-23T21:56:34.994+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T21:51:26.280791+00:00 [queued]>
[2025-02-23T21:56:35.002+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T21:51:26.280791+00:00 [queued]>
[2025-02-23T21:56:35.003+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-23T21:56:35.018+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_to_hdfs> on 2025-02-23 21:51:26.280791+00:00
[2025-02-23T21:56:35.027+0000] {standard_task_runner.py:57} INFO - Started process 55927 to run task
[2025-02-23T21:56:35.030+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_crypto_data_and_upload_to_hdfs', 'upload_to_hdfs', 'manual__2025-02-23T21:51:26.280791+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data.py', '--cfg-path', '/tmp/tmp_rtpa5ee']
[2025-02-23T21:56:35.033+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask upload_to_hdfs
[2025-02-23T21:56:35.090+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T21:51:26.280791+00:00 [running]> on host 95f034191b67
[2025-02-23T21:56:35.177+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_crypto_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T21:51:26.280791+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T21:51:26.280791+00:00'
[2025-02-23T21:56:35.179+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-23T21:56:35.181+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd docker cp /tmp/crypto_historical_data.csv namenode:/tmp/crypto_historical_data.csv && docker cp namenode:/tmp/crypto_historical_data.csv hdfs:/user/root/']
[2025-02-23T21:56:35.196+0000] {subprocess.py:86} INFO - Output:
[2025-02-23T21:56:35.198+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: too many arguments
[2025-02-23T21:56:35.199+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-23T21:56:35.218+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-23T21:56:35.224+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_crypto_data_and_upload_to_hdfs, task_id=upload_to_hdfs, execution_date=20250223T215126, start_date=20250223T215634, end_date=20250223T215635
[2025-02-23T21:56:35.240+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task upload_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 55927)
[2025-02-23T21:56:35.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-23T21:56:35.323+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
