[2025-02-25T15:26:36.063+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-25T15:26:30.603722+00:00 [queued]>
[2025-02-25T15:26:36.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-25T15:26:30.603722+00:00 [queued]>
[2025-02-25T15:26:36.080+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T15:26:36.103+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-25 15:26:30.603722+00:00
[2025-02-25T15:26:36.113+0000] {standard_task_runner.py:57} INFO - Started process 2616 to run task
[2025-02-25T15:26:36.118+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_processing_mapreduce', 'run_mapreduce_job', 'manual__2025-02-25T15:26:30.603722+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/transform_data.py', '--cfg-path', '/tmp/tmpianfbbca']
[2025-02-25T15:26:36.123+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask run_mapreduce_job
[2025-02-25T15:26:36.209+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-25T15:26:30.603722+00:00 [running]> on host 53d736af5afa
[2025-02-25T15:26:36.292+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-25T15:26:36.334+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_processing_mapreduce' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T15:26:30.603722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T15:26:30.603722+00:00'
[2025-02-25T15:26:36.338+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-25T15:26:36.340+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec namenode hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar           -input /user/root/crypto/YYYY=2025/MM=02/DD=25/coingecko_raw.json           -output /user/root/crypto/processed/YYYY=2025/MM=02/DD=25           -mapper /path/to/mapper.py           -reducer /path/to/reducer.py           -file /path/to/mapper.py           -file /path/to/reducer.py\n        ']
[2025-02-25T15:26:36.354+0000] {subprocess.py:86} INFO - Output:
[2025-02-25T15:26:36.356+0000] {subprocess.py:93} INFO - /bin/bash: line 2: docker: command not found
[2025-02-25T15:26:36.357+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-02-25T15:26:36.374+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-02-25T15:26:36.384+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_processing_mapreduce, task_id=run_mapreduce_job, execution_date=20250225T152630, start_date=20250225T152636, end_date=20250225T152636
[2025-02-25T15:26:36.406+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 127.; 2616)
[2025-02-25T15:26:36.452+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-25T15:26:36.486+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
