[2025-02-25T15:33:11.984+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-25T15:33:08.680911+00:00 [queued]>
[2025-02-25T15:33:11.999+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-25T15:33:08.680911+00:00 [queued]>
[2025-02-25T15:33:11.999+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T15:33:12.020+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-25 15:33:08.680911+00:00
[2025-02-25T15:33:12.028+0000] {standard_task_runner.py:57} INFO - Started process 9551 to run task
[2025-02-25T15:33:12.032+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_processing_mapreduce', 'run_mapreduce_job', 'manual__2025-02-25T15:33:08.680911+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/transform_data.py', '--cfg-path', '/tmp/tmp3zc_cr4n']
[2025-02-25T15:33:12.035+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask run_mapreduce_job
[2025-02-25T15:33:12.100+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-25T15:33:08.680911+00:00 [running]> on host 53d736af5afa
[2025-02-25T15:33:12.171+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-25T15:33:12.221+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_processing_mapreduce' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T15:33:08.680911+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T15:33:08.680911+00:00'
[2025-02-25T15:33:12.225+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-25T15:33:12.227+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec namenode hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar           -input /user/root/crypto/YYYY=2025/MM=02/DD=25/crypto_historical_data.csv           -output /user/root/crypto/processed/YYYY=2025/MM=02/DD=25           -mapper /path/to/mapper.py           -reducer /path/to/reducer.py           -file /path/to/mapper.py           -file /path/to/reducer.py\n        ']
[2025-02-25T15:33:12.243+0000] {subprocess.py:86} INFO - Output:
[2025-02-25T15:33:12.247+0000] {subprocess.py:93} INFO - /bin/bash: line 2: docker: command not found
[2025-02-25T15:33:12.248+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-02-25T15:33:12.269+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-02-25T15:33:12.273+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_processing_mapreduce, task_id=run_mapreduce_job, execution_date=20250225T153308, start_date=20250225T153311, end_date=20250225T153312
[2025-02-25T15:33:12.289+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 127.; 9551)
[2025-02-25T15:33:12.325+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-25T15:33:12.351+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
