[2025-02-26T16:55:30.703+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-26T16:50:22.090375+00:00 [queued]>
[2025-02-26T16:55:30.714+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-26T16:50:22.090375+00:00 [queued]>
[2025-02-26T16:55:30.715+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T16:55:30.729+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-26 16:50:22.090375+00:00
[2025-02-26T16:55:30.737+0000] {standard_task_runner.py:57} INFO - Started process 71536 to run task
[2025-02-26T16:55:30.742+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_processing_mapreduce', 'run_mapreduce_job', 'manual__2025-02-26T16:50:22.090375+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/transform_data.py', '--cfg-path', '/tmp/tmpjf24nyps']
[2025-02-26T16:55:30.747+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask run_mapreduce_job
[2025-02-26T16:55:30.809+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_processing_mapreduce.run_mapreduce_job manual__2025-02-26T16:50:22.090375+00:00 [running]> on host 8f39f5b11fbf
[2025-02-26T16:55:30.871+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-02-26T16:55:30.906+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_data_processing_mapreduce' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T16:50:22.090375+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T16:50:22.090375+00:00'
[2025-02-26T16:55:30.908+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T16:55:30.911+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                docker exec namenode bash -c "cd /home &&                 hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar                 -input /user/root/crypto/YYYY=2025/MM=02/DD=26/crypto_historical_data.csv                 -output /user/root/crypto/processed/YYYY=2025/MM=02/DD=26                 -mapper mapper.py                 -reducer reducer.py                 -file /home/mapper.py                 -file /home/reducer.py"\n            ']
[2025-02-26T16:55:30.923+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T16:55:31.683+0000] {subprocess.py:93} INFO - 2025-02-26 16:55:31,680 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-26T16:55:32.426+0000] {subprocess.py:93} INFO - packageJobJar: [/home/mapper.py, /home/reducer.py] [] /tmp/streamjob4629142350279226159.jar tmpDir=null
[2025-02-26T16:55:32.514+0000] {subprocess.py:93} INFO - 2025-02-26 16:55:32,512 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T16:55:32.567+0000] {subprocess.py:93} INFO - 2025-02-26 16:55:32,566 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T16:55:32.568+0000] {subprocess.py:93} INFO - 2025-02-26 16:55:32,566 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T16:55:32.582+0000] {subprocess.py:93} INFO - 2025-02-26 16:55:32,580 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T16:55:32.706+0000] {subprocess.py:93} INFO - 2025-02-26 16:55:32,705 ERROR streaming.StreamJob: Error Launching job : Output directory hdfs://namenode:9000/user/root/crypto/processed/YYYY=2025/MM=02/DD=26 already exists
[2025-02-26T16:55:32.707+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-26T16:55:33.164+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-26T16:55:33.186+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-26T16:55:33.191+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crypto_data_processing_mapreduce, task_id=run_mapreduce_job, execution_date=20250226T165022, start_date=20250226T165530, end_date=20250226T165533
[2025-02-26T16:55:33.209+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 5.; 71536)
[2025-02-26T16:55:33.251+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T16:55:33.277+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
