[2025-02-23T19:16:49.329+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T19:16:41.426386+00:00 [queued]>
[2025-02-23T19:16:49.341+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T19:16:41.426386+00:00 [queued]>
[2025-02-23T19:16:49.342+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-23T19:16:49.365+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_to_hdfs> on 2025-02-23 19:16:41.426386+00:00
[2025-02-23T19:16:49.374+0000] {standard_task_runner.py:57} INFO - Started process 83360 to run task
[2025-02-23T19:16:49.377+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_crypto_data_and_upload_to_hdfs', 'upload_to_hdfs', 'manual__2025-02-23T19:16:41.426386+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data.py', '--cfg-path', '/tmp/tmpxv6_emr7']
[2025-02-23T19:16:49.382+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask upload_to_hdfs
[2025-02-23T19:16:49.456+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T19:16:41.426386+00:00 [running]> on host 95f034191b67
[2025-02-23T19:16:49.563+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_crypto_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T19:16:41.426386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T19:16:41.426386+00:00'
[2025-02-23T19:16:49.565+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-23T19:16:49.568+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'script -q /dev/null bash -c "docker cp /tmp/crypto_historical_data.csv namenode:/tmp/crypto_historical_data.csv && docker exec -it -u root namenode bash -c "hdfs dfs -put -f /tmp/crypto_historical_data.csv /user/hadoop/crypto_historical_data.csv""']
[2025-02-23T19:16:49.589+0000] {subprocess.py:86} INFO - Output:
[2025-02-23T19:16:49.594+0000] {subprocess.py:93} INFO - script: invalid option -- 'p'
[2025-02-23T19:16:49.595+0000] {subprocess.py:93} INFO - Try 'script --help' for more information.
[2025-02-23T19:16:49.597+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-23T19:16:49.619+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-23T19:16:49.625+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_crypto_data_and_upload_to_hdfs, task_id=upload_to_hdfs, execution_date=20250223T191641, start_date=20250223T191649, end_date=20250223T191649
[2025-02-23T19:16:49.648+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task upload_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 83360)
[2025-02-23T19:16:49.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-23T19:16:49.700+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
