[2025-02-23T19:21:51.154+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T19:16:41.426386+00:00 [queued]>
[2025-02-23T19:21:51.164+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T19:16:41.426386+00:00 [queued]>
[2025-02-23T19:21:51.165+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-23T19:21:51.183+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): upload_to_hdfs> on 2025-02-23 19:16:41.426386+00:00
[2025-02-23T19:21:51.193+0000] {standard_task_runner.py:57} INFO - Started process 88983 to run task
[2025-02-23T19:21:51.198+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_crypto_data_and_upload_to_hdfs', 'upload_to_hdfs', 'manual__2025-02-23T19:16:41.426386+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data.py', '--cfg-path', '/tmp/tmpugujkm49']
[2025-02-23T19:21:51.203+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask upload_to_hdfs
[2025-02-23T19:21:51.271+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_crypto_data_and_upload_to_hdfs.upload_to_hdfs manual__2025-02-23T19:16:41.426386+00:00 [running]> on host 95f034191b67
[2025-02-23T19:21:51.367+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_crypto_data_and_upload_to_hdfs' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T19:16:41.426386+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T19:16:41.426386+00:00'
[2025-02-23T19:21:51.369+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-23T19:21:51.372+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'script -q /dev/null bash -c "docker cp /tmp/crypto_historical_data.csv namenode:/tmp/crypto_historical_data.csv && docker exec -it -u root namenode bash -c "hdfs dfs -put -f /tmp/crypto_historical_data.csv /user/hadoop/crypto_historical_data.csv""']
[2025-02-23T19:21:51.386+0000] {subprocess.py:86} INFO - Output:
[2025-02-23T19:21:51.390+0000] {subprocess.py:93} INFO - script: invalid option -- 'p'
[2025-02-23T19:21:51.391+0000] {subprocess.py:93} INFO - Try 'script --help' for more information.
[2025-02-23T19:21:51.392+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-23T19:21:51.414+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-23T19:21:51.420+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fetch_crypto_data_and_upload_to_hdfs, task_id=upload_to_hdfs, execution_date=20250223T191641, start_date=20250223T192151, end_date=20250223T192151
[2025-02-23T19:21:51.438+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task upload_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 88983)
[2025-02-23T19:21:51.458+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-23T19:21:51.484+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
